[package]
name = "mocked"
version = "0.3.0"
edition = "2021"
license-file = "LICENSE"
description = "Your friendly HTTP mock response server"
repository = "https://github.com/herzrasen/mocked.git"
readme = "README.md"

[dependencies]
axum = "0.7.5"
axum-test = "14.9.1"
clap = { version = "4.5.4", features = ["derive"] }
env_logger = "0.11.3"
log = "0.4.21"
serde = { version = "1.0.198", features = ["derive"] }
serde_json = "1.0.116"
serde_yaml = "0.9.34"
tempfile = "3.10.1"
tokio = { version = "1.37.0", features = ["full"] }
tower = "0.4.13"
rand = "0.8.5"
