rules:
  - path: /v1/foo/:bar/:version
    method: GET
    responses:
      - op: or
        matchers:
          - of: PathParamMatcher
            with:
              name: bar
              matches:
                - foo
                - baz
          - of: PathParamMatcher
            with:
              name: version
              matches:
                - 2
        status: 200
        headers:
          Content-Type: application/json
        body: Hello, World