options:
  address: localhost
  port: 15001
  enable_cors: true
  min_response_delay_ms: 100
  max_response_delay_ms: 3000
routes:
  - path: /v1/login
    enable_cors: false
    methods:
      - POST
      - PUT
    conditions:
      - type: HeaderContains
        with:
          name: Authorization
          values:
            - Basic
        response:
          status: 200
          headers:
            Content-Type: application/json
          body:
            include: resp.json
  - path: /v1/search/{type}/{version}
    methods:
      - POST
      - PUT
    conditions:
      - or:
          - type: PathParam
            with:
              name: type
              values:
                - foo
                - bar
          - type: PathParam
            with:
              name: version
              values:
                - 1
                - 2
          - type: BodyContains
            with:
              values: 
                - hello
        response:
          status: 200
          headers:
            Content-Type: application/json
          body: >
            Hello, World
            This is a body
            and it uses multiple
            lines  
  - path: /v1/search
    methods:
      - GET
    conditions:
      - type: QueryContains
        with:
          name: foo
          values:
            - bar
        response:
          status: 200
          headers:
            Content-Type: application/json
          body: >
            Hello, World
            This request contained a query param